package = "marksetta"
version = "scm"
lua = ">=5.1"

[description]
summary = "Ambiguous markup-processor for fast and cozy scientific writing"
maintainer = "merv1n34k"
labels = [ "tex", "markup", "converter", "markdown" ]
license = "MIT"

[source]
dev = "git+file:///Users/alexeystroganov/.github_projects/marksetta"

[dependencies]
# Add your dependencies here
# `busted = ">=2.0"`

[run]
args = [ "lua/main.lua" ]

[build]
type = "builtin"

[build.modules]
"marksetta" = "lua/marksetta/init.lua"
"marksetta.config" = "lua/marksetta/config.lua"
"marksetta.import" = "lua/marksetta/import.lua"
"marksetta.internal" = "lua/marksetta/internal.lua"
"marksetta.export" = "lua/marksetta/export.lua"
"marksetta.json" = "lua/marksetta/json.lua"
